#!/usr/bin/env bun
/**
 * Checks that the specified Docker project's containers are running
 * and writes the dynamic port mappings to .env.local
 */

import { join } from 'path'
import { mkdir } from 'fs/promises'

const projectName = process.env.RAILWAY_PROJECT_NAME
const dockerProjectName = projectName?.toLowerCase()

if (!projectName) {
	console.error('\x1b[31m✗ RAILWAY_PROJECT_NAME not set in environment\x1b[0m')
	process.exit(1)
}

async function getRunningContainers(): Promise<string[]> {
	const proc = Bun.spawn(['docker', 'ps', '--format', '{{.Names}}'])
	const text = await new Response(proc.stdout).text()
	const exitCode = await proc.exited
	if (exitCode !== 0) {
		console.error('\x1b[31m✗ Docker is not available (is it installed and running?)\x1b[0m')
		process.exit(1)
	}
	return text.trim().split('\n').filter(Boolean)
}

async function getContainerPort(containerName: string, containerPort: number): Promise<number> {
	const proc = Bun.spawn(['docker', 'port', containerName, containerPort.toString()])
	const text = await new Response(proc.stdout).text()
	const exitCode = await proc.exited
	if (exitCode !== 0) {
		throw new Error(`Failed to get port for ${containerName}:${containerPort}`)
	}
	// Output format: "0.0.0.0:12345" or "[::]:12345"
	const match = text.trim().match(/:(\d+)$/)
	if (!match) {
		throw new Error(`Could not parse port from: ${text}`)
	}
	return parseInt(match[1], 10)
}

async function writeEnvLocal(redisPort: number): Promise<void> {
	const envPath = join(import.meta.dir, '..', '.env.local')
	const dataPath = join(import.meta.dir, '..', 'db')
	await mkdir(dataPath, { recursive: true })

	const content = `# Auto-generated by check-docker.ts - do not edit
DB_URL=./db/data.sqlite
REDIS_URL=redis://localhost:${redisPort}
`
	await Bun.write(envPath, content)
}

async function main() {
	const running = await getRunningContainers()
	const projectContainers = running.filter((name) =>
		name.toLowerCase().startsWith(`${dockerProjectName}-`)
	)
	const otherContainers = running.filter(
		(name) => !name.toLowerCase().startsWith(`${dockerProjectName}-`)
	)

	if (projectContainers.length === 0) {
		if (otherContainers.length > 0) {
			console.error("\x1b[31m✗ Wrong project's Docker containers are running:\x1b[0m")
			otherContainers.forEach((name) => console.error(`  - ${name}`))
			console.error(`\nRun: \x1b[33mbun run docker:start\x1b[0m`)
		} else {
			console.error(`\x1b[31m✗ No Docker containers running for ${projectName}\x1b[0m`)
			console.error(`\nRun: \x1b[33mbun run docker:start\x1b[0m`)
		}
		process.exit(1)
	}

	// Get the actual port mappings
	const redisContainer = projectContainers.find((name) => name.includes('-redis-'))

	if (!redisContainer) {
		console.error('\x1b[31m✗ Could not find redis container\x1b[0m')
		console.error('Found containers:', projectContainers)
		process.exit(1)
	}

	const redisPort = await getContainerPort(redisContainer, 6379)

	await writeEnvLocal(redisPort)

	console.log(`\x1b[32m✓ Docker verified (${projectContainers.length} containers)\x1b[0m`)
	console.log(`  db: ./db/data.sqlite, redis: localhost:${redisPort}`)
}

main().catch((err) => {
	console.error('\x1b[31m✗ Unexpected error:\x1b[0m', err.message)
	process.exit(1)
})
